# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_delete_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
